version: 2.0

InstallJFrog: &InstallJFrog
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
          
ConfigJFrog: &ConfigJFrog
      - run:
          name: Configure Articatory Instance with JFrog CLI
          # --interactive false
          command: |
                   echo ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD
                   ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD
    
jobs:

  build:
    docker:
      - image: circleci/ruby:2.3-node-browsers
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      <<: *InstallJFrog
      
      <<: *ConfigJFrog
      
      - checkout
      - run:
          name: install vendor bundle
          command: bundle install --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake

  "ruby-2.2":
    docker:
      - image: circleci/ruby:2.3-node-browsers
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      <<: *InstallJFrog
      
      <<: *ConfigJFrog
      
      - checkout
      - run:
          name: install vendor bundle
          command: bundle install --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake

  "ruby-2.3":
    docker:
      - image: circleci/ruby:2.3-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake

  "ruby-2.4":
    docker:
      - image: circleci/ruby:2.4-node
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: rake

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.2"
      #- "ruby-2.3"
      #- "ruby-2.4"
